### ISSUE TITLE
Cannot login with root

### ISSUE THREAD

**Issue by davidq2q** [presslabs/mysql-operator#327] opened 2019-05-22 15:08 UTC
For some weird reason the operator suddenly doesn't set the root password correctly. It did at the beginning of the day but now I cannot login as root user. Created new cluster several times, still same problem.

**Comment by AMecea** [comment] 2019-05-22 16:30
I may be related with #229, the mysql initialization takes too long and the liveness probe kills the container before initializing root user. There will be a fix delivered soon, based on recently  merged PR percona/percona-docker#82 .

Please let me know if it's the same issue. Does the mysql container get restarted?

**Comment by davidq2q** [comment] 2019-05-24 07:33
On the stateful set the first pod does get restarted on initialization twice. Tried some of the solutions on the #229 issue but unfortunately they didn't work.

**Comment by davidq2q** [comment] 2019-05-24 07:41
This is a very annoying bug and makes this operator unusable.

**Comment by AMecea** [comment] 2019-05-24 14:39
This doesn't happen in my environment.  We are using default GKE. Do you have some specific configurations? 

Are you sure that the `mysql` container is restarted and not the `pt-heartbeat`? Usually pt-heartbeat gets restarted several times for the first time, but that it's normal. To see which container is restarted please give me the output of `kubectl describe pod <cluster-name>-mysql-0`

Also what version of the operator do you use?

**Comment by AMecea** [comment] 2019-05-24 18:21
Also, some more debug information will be useful. What is inside of MySQL?
By running the following command you will get mysql shell:
```
kubectl exec -it <cluster-name>-mysql-0 -c mysql -- mysql --defaults-file=/etc/mysql/client.conf
```
This is for version `0.3.0.rc1` for version `0.2.x` the `defaults-file` path for MySQL is `/etc/mysql/client.cnf`

Then querying the user table ( `SELECT * FROM mysql.user;` ) you can see if the `root` user has a password set or not.

Thank you for helping to debug this issue!

**Comment by calind** [comment] 2019-06-04 14:37
Duplicate of #229.

**Closed by calind** 2019-06-04 14:37 UTC
