### ISSUE TITLE
Do gracefull master promotion when scaling down

### ISSUE THREAD

**Issue by AMecea** [presslabs/mysql-operator#217] opened 2019-01-28 17:40 UTC
Now there is a case when node-1 is master and node-0 is slave. During scaling down the cluster, node-1 will be killed during the process, then node-0 will be promoted. This action may end with data loss. 

Will be better, before scaling down, to promote the replica that remains alive as master.

**Comment by calind** [comment] 2019-02-01 09:35
Duplicate of #15.

**Closed by calind** 2019-02-01 09:35 UTC
