### ISSUE TITLE
[ERROR] Slave I/O for channel '': error connecting to master 'repl_lJARV

### ISSUE THREAD

**Issue by HBO2** [presslabs/mysql-operator#143] opened 2018-11-14 11:48 UTC
Hi All,

I have deployed second cluster with operator next to an already existing and 1 master with 2 slaves and on both slaves I get this ERROR:

[ERROR] Slave I/O for channel '': error connecting to master 'repl_lJARV@my-clusterr-mysql-0.my-cluster-cluster-mysql-:3306' - retry-time: 10  retries: 6133, Error_code: 2005

On the other cluster deployed first I get no error like this but  get a the warning described in issue #142

any idea's how to deal with this?
thx

**Comment by AMecea** [comment] 2018-11-14 20:56
Hi @HBO2,

I've tried to reproduce it as you said but I can not. What is your setup exactly? Also, did you use the same secret for both clusters? What version of operator did you use? Did you add some extra configures on the cluster?

Thanks for letting us know about this!

**Comment by HBO2** [comment] 2018-11-14 22:59
Hi @AMecea 

It could be that the first attempt of the creation of cluster I used the same secret, but I deleted this version and I am using a different secret, but I used the same secret for the backup.

please find below the setup:
`apiVersion: mysql.presslabs.org/v1alpha1
kind: MysqlCluster
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"mysql.presslabs.org/v1alpha1","kind":"MysqlCluster","metadata":{"annotations":{},"creationTimestamp":"2018-11-06T13:23:30Z","generation":2,"name":"ain-production-cluster","namespace":"default","resourceVersion":"7562247","selfLink":"/apis/mysql.presslabs.org/v1alpha1/namespaces/default/mysqlclusters/ain-production-cluster","uid":"27319699-e1c7-11e8-b005-0a44ea3fb6f3"},"spec":{"backupSchedule":"0 0 */20 * * *","backupScheduleJobsHistoryLimit":1,"backupSecretName":"my-cluster-backup-secret","backupUri":"s3://backupprod/","minAvailable":"50%","mysqlConf":{"innodb-buffer-pool-size":"536870912","innodb-log-file-size":"134217728"},"mysqlVersion":"5.7","podSpec":{"affinity":{"podAntiAffinity":{"preferredDuringSchedulingIgnoredDuringExecution":[{"podAffinityTerm":{"labelSelector":{"matchLabels":{"app":"mysql-operator","mysql_cluster":"ain-production-cluster"}},"topologyKey":"kubernetes.io/hostname"},"weight":100}]}},"imagePullPolicy":"IfNotPresent","resources":{"requests":{"cpu":"200m","memory":"1Gi"}}},"replicas":3,"secretName":"mysql-production-secret","volumeSpec":{"accessModes":["ReadWriteOnce"],"resources":{"requests":{"storage":"8Gi"}},"storageClassName":"managed-premium"}}}
  creationTimestamp: 2018-11-06T13:23:30Z
  generation: 3
  name: ain-production-cluster
  namespace: default
  resourceVersion: "7577855"
  selfLink: /apis/mysql.presslabs.org/v1alpha1/namespaces/default/mysqlclusters/ain-production-cluster
  uid: 27319699-e1c7-11e8-b005-0a44ea3fb6f3
spec:
  backupSchedule: 0 0 */20 * * *
  backupScheduleJobsHistoryLimit: 1
  backupSecretName: my-cluster-backup-secret
  backupUri: s3://backupprod/
  minAvailable: 50%
  mysqlConf:
    innodb-buffer-pool-size: "536870912"
    innodb-log-file-size: "134217728"
  mysqlVersion: "5.7"
  podSpec:
    affinity:
      podAntiAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
        - podAffinityTerm:
            labelSelector:
              matchLabels:
                app: mysql-operator
                mysql_cluster: ain-production-cluster
            topologyKey: kubernetes.io/hostname
          weight: 100
    imagePullPolicy: IfNotPresent
    resources:
      requests:
        cpu: 200m
        memory: 1Gi
  replicas: 3
  secretName: mysql-production-secret
  volumeSpec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 8Gi
    storageClassName: managed-premium
`

**Comment by AMecea** [comment] 2018-11-20 14:23
This can happen because of a previous cluster that had the same name with this one. So the PVC that was left behind by the previous cluster is reused and the new credentials don't fit. 

This is fixed in version 0.2.0 by #140

**Closed by AMecea** 2018-11-20 14:23 UTC
