### ISSUE TITLE
Auto backups pods don't get deleted after they're completed

### ISSUE THREAD

**Issue by elderapo** [presslabs/mysql-operator#589] opened 2020-08-17 12:10 UTC
When playing with this operator I setup automatic backup every 1 minute (for testing purposes - wouldn't do that in production). The backups were successfully created and uploaded to my s3 bucket but pods wouldn't get automatically deleted after they were done:
```
my-cluster-auto-2020-08-17t11-56-16-backup-5vpd9   0/1     Completed   0          9m5s
my-cluster-auto-2020-08-17t11-56-22-backup-vvts5   0/1     Completed   0          8m59s
my-cluster-auto-2020-08-17t11-56-29-backup-r66d4   0/1     Completed   0          8m52s
my-cluster-auto-2020-08-17t11-56-36-backup-lhzcd   0/1     Completed   0          8m45s
my-cluster-auto-2020-08-17t11-56-43-backup-pk47m   0/1     Completed   0          8m38s
my-cluster-auto-2020-08-17t11-56-50-backup-vmbfn   0/1     Completed   0          8m31s
my-cluster-auto-2020-08-17t11-56-57-backup-pcz7p   0/1     Completed   0          8m24s
my-cluster-auto-2020-08-17t11-57-04-backup-j6pfb   0/1     Completed   0          8m17s
my-cluster-auto-2020-08-17t11-57-10-backup-hdt84   0/1     Completed   0          8m11s
my-cluster-auto-2020-08-17t11-57-16-backup-bnfgr   0/1     Completed   0          8m5s
my-cluster-auto-2020-08-17t11-57-23-backup-45fng   0/1     Completed   0          7m58s
my-cluster-auto-2020-08-17t11-57-30-backup-7k4hx   0/1     Completed   0          7m51s
my-cluster-auto-2020-08-17t11-57-40-backup-wmsdh   0/1     Completed   0          7m41s
my-cluster-auto-2020-08-17t11-57-50-backup-d5z59   0/1     Completed   0          7m31s
my-cluster-auto-2020-08-17t11-58-00-backup-fzjhh   0/1     Completed   0          7m21s
my-cluster-auto-2020-08-17t11-58-10-backup-zwhd4   0/1     Completed   0          7m11s
my-cluster-auto-2020-08-17t11-58-20-backup-hxczp   0/1     Completed   0          7m1s
my-cluster-auto-2020-08-17t11-58-30-backup-wtzg5   0/1     Completed   0          6m51s
my-cluster-auto-2020-08-17t11-58-40-backup-ljjxf   0/1     Completed   0          6m41s
my-cluster-auto-2020-08-17t11-58-50-backup-k8l7d   0/1     Completed   0          6m31s
my-cluster-auto-2020-08-17t11-59-00-backup-b98kd   0/1     Completed   0          6m21s
my-cluster-auto-2020-08-17t11-59-10-backup-h86cb   0/1     Completed   0          6m11s
my-cluster-auto-2020-08-17t11-59-20-backup-hstfz   0/1     Completed   0          6m1s
my-cluster-auto-2020-08-17t11-59-30-backup-6llt7   0/1     Completed   0          5m51s
my-cluster-auto-2020-08-17t11-59-40-backup-9jx2c   0/1     Completed   0          5m41s
my-cluster-auto-2020-08-17t11-59-50-backup-7l6xw   0/1     Completed   0          5m31s
my-cluster-auto-2020-08-17t12-00-00-backup-gbjtv   0/1     Completed   0          5m21s
my-cluster-auto-2020-08-17t12-00-10-backup-2h6nx   0/1     Completed   0          5m11s
my-cluster-auto-2020-08-17t12-00-20-backup-pgp4p   0/1     Completed   0          5m1s
my-cluster-auto-2020-08-17t12-00-30-backup-mvmg9   0/1     Completed   0          4m51s
my-cluster-auto-2020-08-17t12-00-40-backup-pvhkz   0/1     Completed   0          4m41s
my-cluster-auto-2020-08-17t12-00-50-backup-77srx   0/1     Completed   0          4m31s
my-cluster-auto-2020-08-17t12-01-00-backup-w9fwh   0/1     Completed   0          4m21s
my-cluster-auto-2020-08-17t12-01-10-backup-xmv4r   0/1     Completed   0          4m11s
my-cluster-auto-2020-08-17t12-01-20-backup-pvkn4   0/1     Completed   0          4m1s
my-cluster-auto-2020-08-17t12-01-30-backup-njfv4   0/1     Completed   0          3m51s
my-cluster-auto-2020-08-17t12-01-40-backup-vfh8k   0/1     Completed   0          3m41s
my-cluster-auto-2020-08-17t12-02-00-backup-5dhqp   0/1     Completed   0          3m21s
my-cluster-auto-2020-08-17t12-03-00-backup-6gnqr   0/1     Completed   0          2m21s
```

**Comment by AMecea** [comment] 2020-08-28 07:26
Duplicate of #577

**Closed** 2020-08-28 12:40 UTC
